# Generated by Django 3.2.13 on 2023-07-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20230703_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Visualizar catalogos')]},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[['Particular', 'Particular'], ['transporte', 'transporte'], ['carga', 'carga']], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[['Fiat', 'Fiat'], ['Chevrolet', 'Chevrolet'], ['Ford', 'Ford'], ['Toyota', 'Toyota']], default='Ford', max_length=20),
        ),
    ]
