# Generated by Django 3.2.13 on 2024-02-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_auto_20240201_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='año',
            field=models.CharField(default='2024', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[['Particular', 'Particular'], ['Transporte', 'Transporte'], ['Carga', 'Carga']], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='condicion',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Seminuevo', 'Seminuevo'], ['Usado', 'Usado']], default='Nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[['Abarth', 'Abarth'], ['BMW', 'BMW'], ['Dacia', 'Dacia'], ['Infiniti', 'Infiniti'], ['Kia', 'Kia'], ['Land Rover', 'Land Rover'], ['Mercedes-Benz', 'Mercedes-Benz'], ['Opel', 'Opel'], ['Rolls-Royce', 'Rolls-Royce'], ['Subaru', 'Subaru'], ['Volkswagen', 'Volkswagen'], ['Alfa Romeo', 'TAlfa Romeo'], ['Cadillac', 'Cadillac'], ['Ferrari', 'Ferrari'], ['Isuzu', 'Isuzu'], ['KTM', 'KTM'], ['Lexus', 'Lexus'], ['Mini', 'Mini'], ['Peugeot', 'Peugeot'], ['Seat', 'Seat'], ['Suzuki', 'Suzuki'], ['Volvo', 'Volvo'], ['Aston Martin', 'Aston Martin'], ['Toyota', 'Toyota'], ['Caterham', 'Caterham'], ['Iveco', 'Iveco'], ['Lada', 'Lada'], ['Lotus', 'Lotus'], ['Fiat', 'Fiat'], ['Mitsubishi', 'Mitsubishi'], ['Piaggio', 'Piaggio'], ['Skoda', 'Skoda'], ['Tata', 'Tata'], ['Audi', 'Audi'], ['Jaguar', 'Jaguar'], ['Lamborghini', 'Lamborghini'], ['Maserati', 'Maserati'], ['Chevrolet', 'Chevrolet'], ['Ford', 'Ford'], ['Morgan', 'Morgan'], ['Porsche', 'Porsche'], ['Smart', 'Smart'], ['Tesla', 'Tesla'], ['Bentley', 'Bentley'], ['Citroen', 'Citroen'], ['Honda', 'Honda'], ['Jeep', 'Jeep'], ['Lancia', 'Lancia'], ['Mazda', 'Mazda'], ['Nissan', 'Nissan'], ['Renault', 'Renault'], ['SsangYong', 'SsangYong'], ['Toyota', 'Toyota']], default='Ford', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
